/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rw.gov.CarWashMgt.view;

import Utility.BDUtility;
import Validations.CarWash;
import java.awt.Color;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.text.MessageFormat;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import rw.gov.CarWashMgt.model.Cars;
import rw.gov.CarWashMgt.service.CarsService;


/**
 *
 * @author ADMIN
 */
public class CarsPage extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form CarsPage
     */
    public CarsPage() {
        initComponents();
        BDUtility.setImage(this, "images/abc1.jpg", 1000, 550);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
        addColumnsHeaderNameToCarsTable();
    }
    
    private void addColumnsHeaderNameToCarsTable(){
        tableModel.setColumnCount(0);
        tableModel.addColumn("Car Id");
        tableModel.addColumn("Car Plate Number");
        tableModel.addColumn("Car Brand");
        tableModel.addColumn("Car Mgn_Year");
        tableModel.addColumn("Car Owner");
        tableModel.addColumn("Fuel Type");
        tableModel.addColumn("Transmission Type");
        carsTable.setModel(tableModel);
    }
    
    private void addRowsDataToCarsTable(){
        try{
            tableModel.setRowCount(0);
            Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",81);
            CarsService service = (CarsService)theRegistry.lookup("cars");
            List<Cars> cars = service.findAll();
            for(Cars theCars : cars){
                tableModel.addRow(new Object[]{
                    theCars.getId(),
                    theCars.getPlateNo(),
                    theCars.getCarBrand(),
                    theCars.getMgnYear(),
                    theCars.getOwner(),
                    theCars.getFuelType(),
                    theCars.getTransmissionType(),
                    
                });
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        exitBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        carPlateNumberTxt = new javax.swing.JTextField();
        carBrandTxt = new javax.swing.JTextField();
        carMgnYearTxt = new javax.swing.JTextField();
        carOwnerTxt = new javax.swing.JTextField();
        carFuelCombo = new javax.swing.JComboBox<>();
        carTransmissionCombo = new javax.swing.JComboBox<>();
        carRegisterBtn = new javax.swing.JButton();
        carUpdateBtn = new javax.swing.JButton();
        carDeleteBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        carSearchTxt = new javax.swing.JTextField();
        carSearchBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        carsTable = new javax.swing.JTable();
        carClearBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        carPrintBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setUndecorated(true);

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exitBtn.setText("X");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Car Plate Number");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Car Brand");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Car Magnifactured Year");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Car Owner");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Car Fuel Type");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Car Transmission Type");

        carPlateNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPlateNumberTxtActionPerformed(evt);
            }
        });

        carFuelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Gasoil", "Fuel", "Electric", "Hybrid" }));

        carTransmissionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Automatic", "Manual" }));

        carRegisterBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carRegisterBtn.setText("Register");
        carRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carRegisterBtnActionPerformed(evt);
            }
        });

        carUpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carUpdateBtn.setText("Update");
        carUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carUpdateBtnActionPerformed(evt);
            }
        });

        carDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carDeleteBtn.setText("Delete");
        carDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carDeleteBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel18.setText("Car Id");

        carSearchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carSearchBtn.setText("Search");
        carSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carSearchBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CARS MANAGEMENT");

        carsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(carsTable);

        carClearBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carClearBtn.setText("Clear");
        carClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carClearBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        carPrintBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        carPrintBtn.setText("Print");
        carPrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPrintBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(carSearchBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(169, 169, 169)
                                        .addComponent(carSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(carTransmissionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(carFuelCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(carOwnerTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(carMgnYearTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(carBrandTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(carPlateNumberTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(carRegisterBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(carUpdateBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(carDeleteBtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(displayBtn))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(carPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(carClearBtn)))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(330, 330, 330)
                        .addComponent(exitBtn))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(exitBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carClearBtn)
                    .addComponent(carPrintBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(carPlateNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(carBrandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(carMgnYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(carOwnerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(carFuelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(carTransmissionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carDeleteBtn)
                            .addComponent(carUpdateBtn)
                            .addComponent(carRegisterBtn)
                            .addComponent(displayBtn))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(29, 29, 29)
                        .addComponent(carSearchBtn))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void carPlateNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPlateNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPlateNumberTxtActionPerformed

    private void carRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carRegisterBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(carPlateNumberTxt.getText().trim().isEmpty() || carBrandTxt.getText().trim().isEmpty() || carMgnYearTxt.getText().trim().isEmpty() || carOwnerTxt.getText().trim() .isEmpty() || carFuelCombo.getSelectedItem().equals("Select") || carTransmissionCombo.getSelectedItem().equals("Select")){
                JOptionPane.showMessageDialog(null, "All Fields are required", "Missing", JOptionPane.ERROR_MESSAGE);
            }else{
                Cars theCars = new Cars();
                theCars.setPlateNo(carPlateNumberTxt.getText());
                theCars.setCarBrand(carBrandTxt.getText());
                int year = Integer.parseInt(carMgnYearTxt.getText());
                theCars.setMgnYear(year);
                theCars.setOwner(carOwnerTxt.getText());
                theCars.setFuelType(carFuelCombo.getSelectedItem().toString());
                theCars.setTransmissionType(carTransmissionCombo.getSelectedItem().toString());
                CarWash dao = new CarWash();
                if(dao.checkCarExist(theCars)==0){
                if(carPlateNumberTxt.getText().matches("^[A-Z]{3}[0-9]{3}[A-Z]{1}") && carBrandTxt.getText().length()>=2 && carOwnerTxt.getText().length()>=2){
                    int a = JOptionPane.showConfirmDialog(null, "Register?","APPROVE",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
                    if(a==0){
                        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",81);
                        CarsService service = (CarsService)theRegistry.lookup("cars");
                        Cars cars = service.saveCars(theCars);
                        if(cars!=null){
                            JOptionPane.showMessageDialog(this, "Data Saved Successful");
                        }else{
                            JOptionPane.showMessageDialog(this, "Data Not Saved");
                        }
                    }if(a==1){
                        carPlateNumberTxt.setText("");
                        carBrandTxt.setText("");
                        carMgnYearTxt.setText("");
                        carOwnerTxt.setText("");
                        carFuelCombo.setSelectedIndex(0);
                        carTransmissionCombo.setSelectedIndex(0);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Enter Values with Accurate Lenght", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
                }else{
                    JOptionPane.showMessageDialog(this, "Car Already Exist");
                }

            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_carRegisterBtnActionPerformed

    private void carUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carUpdateBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(carSearchTxt.getText().trim().isEmpty() || carPlateNumberTxt.getText().trim().isEmpty() || carBrandTxt.getText().trim().isEmpty() || carMgnYearTxt.getText().trim().isEmpty() || carOwnerTxt.getText().trim() .isEmpty() || carFuelCombo.getSelectedItem().equals("Select") || carTransmissionCombo.getSelectedItem().equals("Select")){
                JOptionPane.showMessageDialog(null, "Search the Car to Update", "Search First", JOptionPane.ERROR_MESSAGE);
            }else{
                Cars theCars = new Cars();
                int id = Integer.parseInt(carSearchTxt.getText());
                theCars.setId(id);
                theCars.setPlateNo(carPlateNumberTxt.getText());
                theCars.setCarBrand(carBrandTxt.getText());
                int year = Integer.parseInt(carMgnYearTxt.getText());
                theCars.setMgnYear(year);
                theCars.setOwner(carOwnerTxt.getText());
                theCars.setFuelType(carFuelCombo.getSelectedItem().toString());
                theCars.setTransmissionType(carTransmissionCombo.getSelectedItem().toString());
                
                if(carPlateNumberTxt.getText().matches("^[A-Z]{3}[0-9]{3}[A-Z]") && carBrandTxt.getText().length()>=2 && carOwnerTxt.getText().length()>=2){
                    int a = JOptionPane.showConfirmDialog(null, "Approve","UPDATE",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(a==0){
                        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",81);
                        CarsService service = (CarsService)theRegistry.lookup("cars");
                        Cars cars = service.updateCars(theCars);
                        if(cars!=null){
                            JOptionPane.showMessageDialog(this, "Data Updated Successful");
                        }else{
                            JOptionPane.showMessageDialog(this, "Data Not Updated");
                        }
                    }if(a==1){
                        carPlateNumberTxt.setText("");
                        carBrandTxt.setText("");
                        carMgnYearTxt.setText("");
                        carOwnerTxt.setText("");
                        carFuelCombo.setSelectedIndex(0);
                        carTransmissionCombo.setSelectedIndex(0);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Enter Values with Accurate Lenght", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_carUpdateBtnActionPerformed

    private void carDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carDeleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(carSearchTxt.getText().trim().isEmpty() || carPlateNumberTxt.getText().trim().isEmpty() || carBrandTxt.getText().trim().isEmpty() || carMgnYearTxt.getText().trim().isEmpty() || carOwnerTxt.getText().trim() .isEmpty() || carFuelCombo.getSelectedItem().equals("Select") || carTransmissionCombo.getSelectedItem().equals("Select")){
                JOptionPane.showMessageDialog(null, "Search the Car to Delete", "Search First", JOptionPane.ERROR_MESSAGE);
            }else{
                Cars theCars = new Cars();
                int id = Integer.parseInt(carSearchTxt.getText());
                theCars.setId(id);
                theCars.setPlateNo(carPlateNumberTxt.getText());
                theCars.setCarBrand(carBrandTxt.getText());
                int year = Integer.parseInt(carMgnYearTxt.getText());
                theCars.setMgnYear(year);
                theCars.setOwner(carOwnerTxt.getText());
                theCars.setFuelType(carFuelCombo.getSelectedItem().toString());
                theCars.setTransmissionType(carTransmissionCombo.getSelectedItem().toString());
                if(carPlateNumberTxt.getText().matches("^[A-Z]{3}[0-9]{3}[A-Z]") && carBrandTxt.getText().length()>=2 && carOwnerTxt.getText().length()>=2){
                    int a = JOptionPane.showConfirmDialog(null, "Approve","DELETE",JOptionPane.YES_NO_CANCEL_OPTION);
                    if(a==0){
                        Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",81);
                        CarsService service = (CarsService)theRegistry.lookup("cars");
                        Cars cars = service.deleteCars(theCars);
                        if(cars!=null){
                            JOptionPane.showMessageDialog(this, "Data Deleted Successful");
                        }else{
                            JOptionPane.showMessageDialog(this, "Data Not Deleted");
                        }
                    }if(a==1){
                        carPlateNumberTxt.setText("");
                        carBrandTxt.setText("");
                        carMgnYearTxt.setText("");
                        carOwnerTxt.setText("");
                        carFuelCombo.setSelectedIndex(0);
                        carTransmissionCombo.setSelectedIndex(0);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Enter Values with Accurate Lenght", "ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_carDeleteBtnActionPerformed

    private void carSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carSearchBtnActionPerformed
        // TODO add your handling code here:
        try{
            if(carSearchTxt.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Enter the Car Id", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                Cars theCars = new Cars();
                int id = Integer.parseInt(carSearchTxt.getText());
                theCars.setId(id);
                Registry theRegistry = LocateRegistry.getRegistry("127.0.0.1",81);
                CarsService service = (CarsService)theRegistry.lookup("cars");
                Cars cars = service.searchCars(theCars);
                if(cars!=null){
                    carPlateNumberTxt.setText("");
                    carBrandTxt.setText("");
                    carMgnYearTxt.setText("");
                    carOwnerTxt.setText("");
                    carFuelCombo.setSelectedIndex(0);
                    carTransmissionCombo.setSelectedIndex(0);
                    tableModel.setRowCount(0);
                    tableModel.addRow(new Object[]{
                    cars.getId(),
                    cars.getPlateNo(),
                    cars.getCarBrand(),
                    cars.getMgnYear(),
                    cars.getOwner(),
                    cars.getFuelType(),
                    cars.getTransmissionType(),
                    
                });
                }else{
                    JOptionPane.showMessageDialog(this, "Data not Found");
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_carSearchBtnActionPerformed

    private void carsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsTableMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = carsTable.getSelectedRow();
        carSearchTxt.setText(tableModel.getValueAt(selectedRowIndex, 0).toString());
        carPlateNumberTxt.setText(tableModel.getValueAt(selectedRowIndex, 1).toString());
        carBrandTxt.setText(tableModel.getValueAt(selectedRowIndex, 2).toString());
        carMgnYearTxt.setText(tableModel.getValueAt(selectedRowIndex, 3).toString());
        carOwnerTxt.setText(tableModel.getValueAt(selectedRowIndex, 4).toString());
        carFuelCombo.setSelectedItem(tableModel.getValueAt(selectedRowIndex, 5).toString());
        carTransmissionCombo.setSelectedItem(tableModel.getValueAt(selectedRowIndex, 6).toString());
    }//GEN-LAST:event_carsTableMouseClicked

    private void carClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carClearBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "DO YOU WANT TO CLEAR EVERYTHING", "SELECT", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(a==0){
            tableModel.setRowCount(0);

            carSearchTxt.setText("");
            carPlateNumberTxt.setText("");
            carBrandTxt.setText("");
            carMgnYearTxt.setText("");
            carOwnerTxt.setText("");
            carFuelCombo.setSelectedIndex(0);
            carTransmissionCombo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_carClearBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        addColumnsHeaderNameToCarsTable();
        addRowsDataToCarsTable();
    }//GEN-LAST:event_displayBtnActionPerformed

    private void carPrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPrintBtnActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Cars List");
        MessageFormat footer = new MessageFormat("*****Car Wash*****");
        try{
            carsTable.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_carPrintBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carBrandTxt;
    private javax.swing.JButton carClearBtn;
    private javax.swing.JButton carDeleteBtn;
    private javax.swing.JComboBox<String> carFuelCombo;
    private javax.swing.JTextField carMgnYearTxt;
    private javax.swing.JTextField carOwnerTxt;
    private javax.swing.JTextField carPlateNumberTxt;
    private javax.swing.JButton carPrintBtn;
    private javax.swing.JButton carRegisterBtn;
    private javax.swing.JButton carSearchBtn;
    private javax.swing.JTextField carSearchTxt;
    private javax.swing.JComboBox<String> carTransmissionCombo;
    private javax.swing.JButton carUpdateBtn;
    private javax.swing.JTable carsTable;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
